import { useState } from 'react'
import axios from 'axios'
import Header from './components/Header'
import UploadSection from './components/UploadSection'
import ResultsSection from './components/ResultsSection'
import ErrorSection from './components/ErrorSection'
import Footer from './components/Footer'
import './App.css'
import './components.css'

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000'

function App() {
  const [selectedFile, setSelectedFile] = useState(null)
  const [preview, setPreview] = useState(null)
  const [results, setResults] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  const handleFileSelect = (file) => {
    if (!file.type.startsWith('image/')) {
      setError('Hanya file gambar yang didukung!')
      return
    }

    setSelectedFile(file)
    setError(null)

    const reader = new FileReader()
    reader.onload = (e) => setPreview(e.target.result)
    reader.readAsDataURL(file)
  }

  const handleRemoveFile = () => {
    setSelectedFile(null)
    setPreview(null)
  }

  const handlePredict = async () => {
    if (!selectedFile) {
      setError('Silakan pilih file terlebih dahulu!')
      return
    }

    setLoading(true)
    setError(null)

    try {
      const formData = new FormData()
      formData.append('file', selectedFile)

      const response = await axios.post(`${API_BASE_URL}/predict`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
      })

      setResults(response.data)
    } catch (err) {
      console.error('Error:', err)
      setError(
        err.response?.data?.detail ||
        err.message ||
        'Terjadi kesalahan saat menganalisis gambar. Pastikan API server berjalan di ' + API_BASE_URL
      )
    } finally {
      setLoading(false)
    }
  }

  const handleReset = () => {
    setSelectedFile(null)
    setPreview(null)
    setResults(null)
    setError(null)
  }

  const handleDownload = () => {
    if (!results) return

    const timestamp = new Date().toLocaleString('id-ID')
    let content = `HASIL ANALISIS PENYAKIT TANAMAN\n`
    content += `${'='.repeat(40)}\n\n`
    content += `Tanggal/Waktu: ${timestamp}\n\n`
    content += `DIAGNOSIS UTAMA:\n`
    content += `-`.repeat(40) + `\n`
    content += `Penyakit: ${formatClassName(results.predicted_class)}\n`
    content += `Akurasi: ${results.confidence}%\n\n`
    content += `TOP 5 PREDIKSI:\n`
    content += `-`.repeat(40) + `\n`

    results.top5.forEach((pred, index) => {
      content += `${index + 1}. ${formatClassName(pred.class)} (${pred.confidence})\n`
    })

    content += `\n${'='.repeat(40)}\n`
    content += `Generated by Plant Disease Detection System\n`

    const element = document.createElement('a')
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content))
    element.setAttribute('download', `plant_disease_analysis_${Date.now()}.txt`)
    element.style.display = 'none'

    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const formatClassName = (className) => {
    return className
      .replace(/_/g, ' ')
      .replace(/___/g, ' - ')
      .split(' ')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join(' ')
  }

  return (
    <div className="container">
      <Header />

      <main className="main-content">
        {!results && !loading && !error && (
          <UploadSection
            preview={preview}
            onFileSelect={handleFileSelect}
            onRemoveFile={handleRemoveFile}
            onPredict={handlePredict}
            selectedFile={selectedFile}
          />
        )}

        {loading && (
          <div className="loading">
            <div className="spinner"></div>
            <p>Menganalisis gambar...</p>
          </div>
        )}

        {results && (
          <ResultsSection
            results={results}
            preview={preview}
            onReset={handleReset}
            onDownload={handleDownload}
            formatClassName={formatClassName}
          />
        )}

        {error && (
          <ErrorSection error={error} onRetry={handleReset} />
        )}
      </main>

      <Footer />
    </div>
  )
}

export default App
